### ISSUE TITLE
(Feature) Prevent exit on connection errors

### ISSUE THREAD

**Issue by phahulin** [poanetwork/parity-orchestrator#2]
**Problem**: At the present moment if orchestrator fails to establish connection to parity or callback to 30303 is unsuccessful, it will immediately stop. When started, parity takes some time to become fully operational and sync with the network, furthermore, the moment rpc is ready cannot be reliably tracked from outside, so it makes it difficult to automate pairing orchestrator with parity.

**Possible solution**: if connection to rpc cannot be established or callback to 30303 fails - retry it periodically with some interval

**Comment by yrashk** [comment]
Note: while I don't particularly endorse this, the "callback" can be effectively circumvented by setting this in the config file:

```toml
[address]
type = "manual"
ip = "127.0.0.1"
```

But ultimately, if your node is not available to the "outside world" (whatever is the definition of that), what sense would it make to advertise it? Outside of some edge case scenarios that I might be not familiar with.

Anyway. I will add functionality to wait for the connections to become available.

**Comment by phahulin** [comment]
I agree that it doesn't make sense to advertise enodes if noone can connect to it. However, it maybe only temporarily unavailable (e.g. parity is still starting up or was briefly restarted)

**Comment by yrashk** [comment]
Brief restart is narrow window possibility, indeed. But basically, Orchestrator first connects to JSON RPC API before doing the callback. So if the first one doesn't work, it'll never get to the callback.

Anyway, I will implement re-tries there (for both).
